---

- name: Create /var/www directory
  file:
    path: /var/www
    state: directory
    owner: root
    group: root
    mode: '0755'
    
- name: Update package list
  yum:
    name: '*'
    state: latest

- name: Install EPEL repository
  become: true
  command: amazon-linux-extras install -y nginx1

- name: Copy nginx.conf file to /etc/nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Start Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started
