---

- name: creates directory
  file: 
    path: /home/ec2-user/dist
    state: directory

- name: Extract the zipped artifact
  unarchive:
    src: /var/jenkins_home/workspace/vuejs-pipeline/artifact.tar.gz
    dest: /home/ec2-user/dist

- name: Move dist folder to /var/www
  become: true
  ansible.builtin.file:
    src: /home/ec2-user/dist
    dest: /var/www/
    state: directory

- name: Start Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: restarted

