---

- name: "configuration of the server." 
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 600

    - name: "install python for Ansible."
      become: yes
      apt:
        name: python3
        state: latest
        
  roles:
    - config-server
    - deploy